name: Coverage

on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find pr number
        uses: jwalton/gh-find-current-pr@v1
        id: find-pr-number

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          package-manager: pnpm
          prnumber: ${{ steps.find-pr-number.outputs.number }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
